name: CI (exhbma)

on: push

jobs:
  ci-fs-bma:
    name: "CI: exhbma package"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Poetry # GITHUB_PATH is updated from next step
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH

      - name: Setup Poetry
        run: |
          poetry config virtualenvs.in-project true

      - name: Cache venv
        id: cache-venv
        uses: actions/cache@v2
        with:
          path: .venv
          key: ${{ runner.os }}-${{ hashFiles('poetry.lock') }}

      - name: Install Python packages
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: poetry install

      - name: Format
        run: |
          make format
          test -z "$(git status -s)"

      - name: Lint
        run: make lint

      - name: Test(full)
        run: make test-full

      - name: Check requirements.txt for sphinx deployment
        run: exit $(poetry export -f requirements.txt | diff docs/requirements.txt - | wc -l)
